# Generated by Django 5.0.7 on 2024-07-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('brief', models.TextField()),
                ('full_text', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
