# Generated by Django 5.0.6 on 2024-07-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_date', models.DateField()),
                ('token', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('floor_number', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('msquare', models.IntegerField()),
                ('total_price', models.BigIntegerField()),
                ('price_per_msquare', models.BigIntegerField()),
                ('production_year', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('elevator', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('storeroom', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_date', models.DateField()),
                ('token', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('land_msquare', models.IntegerField()),
                ('total_price', models.BigIntegerField()),
                ('price_per_msquare', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_date', models.DateField()),
                ('token', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('land_msquare', models.IntegerField()),
                ('msquare', models.IntegerField()),
                ('total_price', models.BigIntegerField()),
                ('price_per_msquare', models.BigIntegerField()),
                ('production_year', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('storeroom', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('balcony', models.BooleanField()),
            ],
        ),
    ]
